"""IngestService — orchestrator for the full ETL pipeline (E → T → L).

This is the only place that knows both data_loader and data_processing.
"""
from __future__ import annotations
import asyncio
import os
from pathlib import Path

from src.data_loader.domain.models.audio_file import AudioFile, AudioSource
from src.data_loader.domain.models.download_response import DownloadStatus
from src.data_loader.application.entrypoints import run_data_loader
from src.data_processing.application.entrypoints import run_data_processing
from src.data_ingest.domain.models.ingest_record import IngestRecord, IngestStatus

from src.shared.infrastructure.postgres.client import get_session
from src.song_analysis.domain.models.song_analysis import SongAnalysis, AnalysisStatus
from src.song_analysis.infrastructure.repositories.song_analysis_repository import SongAnalysisRepository


class IngestService:
    """Orchestrates the full ETL run for one audio source URL.

    Flow:
        1. E — run_data_loader()   : download → WAV
        2. T — run_data_processing(): WAV → stems → beats → segments → features
        3. L — SongAnalysisRepository.save_domain(): persist to PostgreSQL

    Only this class knows both data_loader and data_processing.
    Neither module knows about each other.
    """

    def _tmp_dir(self, analysis_id: str) -> Path:
        """Persistent working directory inside the mounted data volume."""
        base = Path(os.getenv("DATA_DIR", "/data")) / "tmp" / analysis_id
        base.mkdir(parents=True, exist_ok=True)
        return base

    async def run(
        self,
        analysis_id: str,
        source_url: str,
        user_id: str,
        song_title: str = "",
    ) -> IngestRecord:
        """Run the full E → T → L pipeline for one song.

        Args:
            analysis_id: UUID for this analysis run (pre-generated by caller)
            source_url:  YouTube URL or local file path
            user_id:     Owner of the analysis
            song_title:  Optional title override

        Returns:
            IngestRecord with final status and error_message if failed.
        """
        record = IngestRecord(analysis_id=analysis_id, status=IngestStatus.LOADING)

        # ── Check cache — skip if already analyzed ───────────────────────────
        async with get_session() as session:
            cached = await SongAnalysisRepository(session).get_by_url(source_url)
        if cached.is_ok:
            record.status = IngestStatus.DONE
            return record

        # ── E: Extract ───────────────────────────────────────────────────────
        audio_file = AudioFile.from_url(
            source_url=source_url,
            analysis_id=analysis_id,
            dest_dir=self._tmp_dir(analysis_id),
        )
        response = run_data_loader(audio_file)
        if response.is_err:
            record.fail(response.error)
            return record

        # ── T: Transform ─────────────────────────────────────────────────────
        record.status = IngestStatus.PROCESSING
        processed = run_data_processing(response)
        if processed.is_failed:
            record.fail(processed.error)
            return record

        # ── L: Load ──────────────────────────────────────────────────────────
        record.status = IngestStatus.SAVING
        analysis = SongAnalysis(
            id=analysis_id,
            user_id=user_id,
            source_url=source_url,
            song_title=song_title,
            status=AnalysisStatus.PROCESSING,
            tempo_bpm=processed.tempo_bpm,
        )
        analysis.mark_done(
            key="",             # chord_key detection: Kỳ 2 (MERT model)
            bpm=processed.tempo_bpm or 0.0,
            timeline=[],        # chord_timeline: Kỳ 2
            sheet={},           # chord_sheet:    Kỳ 2
            plan=[],            # learning_plan:  Kỳ 2
        )

        async with get_session() as session:
            await SongAnalysisRepository(session).save_domain(analysis)

        record.status = IngestStatus.DONE
        return record
